---
- name: restart prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: restart grafana
  become: true
  ansible.builtin.service:
    name: grafana
    state: restarted

- name: restart loki
  become: true
  ansible.builtin.service:
    name: loki
    state: restarted
