# Prometheus
prometheus_dir_conf: /home/ansible/.config/prometheus
prometheus_dir_data: /var/opt/prometheus_data
prometheus_version: 3.14.0

# Grafana
grafana_version: "latest"

# Network settings
grafana_http_port: 3000
grafana_domain: "{{ ansible_host }}"
grafana_root_url: "http://{{ grafana_domain }}:{{ grafana_http_port }}"

# Security settings
grafana_admin_user: "{{ lookup('amazon.aws.aws_ssm', '/lab/observability/grafana-admin-user' ) }}"
grafana_admin_password: "{{ lookup('amazon.aws.aws_ssm', '/lab/observability/grafana-admin-password' ) }}"
grafana_secret_key: "{{ lookup('amazon.aws.aws_ssm', '/lab/observability/grafana-secret-key' ) }}"
grafana_disable_gravatar: true
grafana_allow_sign_up: false

# Database settings (default: sqlite3)
grafana_database_type: "sqlite3"
grafana_database_host: ""
grafana_database_name: "grafana"
grafana_database_user: ""
grafana_database_password: ""

# SMTP settings for email alerts
grafana_smtp_enabled: false

# Datasources to provision
grafana_datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    is_default: true
    editable: false
  - name: Loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    is_default: false
    editable: false

# Plugins to install
grafana_plugins:
  - grafana-clock-panel
  - grafana-polystat-panel

# Log settings
grafana_log_mode: "console file"
grafana_log_level: "info"

# Anonymous access
grafana_anonymous_enabled: false
grafana_anonymous_org_role: "Viewer"
