---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - python3-debian
      - wget
      - gnupg
    state: present
    update_cache: yes

- name: Add Grafana APT repository
  ansible.builtin.deb822_repository:
    name: grafana
    types:
      - deb
    uris: https://apt.grafana.com
    suites:
      - stable
    components:
      - main
    signed_by: https://apt.grafana.com/gpg-full.key
    state: present

- name: Install Grafana and Loki
  ansible.builtin.apt:
    pkg:
      - "grafana{% if grafana_version != 'latest' %}={{ grafana_version }}{% endif %}"
      - loki
    state: "{{ 'present' if grafana_version != 'latest' else 'latest' }}"
    update_cache: yes
  notify:
    - restart grafana
    - restart loki

- name: Apply main Grafana configuration (grafana.ini)
  ansible.builtin.template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: "0640"
  become: true
  notify: restart grafana

- name: Provision data sources into Grafana
  ansible.builtin.copy:
    dest: /etc/grafana/provisioning/datasources/automatic.yaml
    owner: root
    group: grafana
    mode: "0640"
    content: "{{ {'apiVersion': 1, 'datasources': grafana_datasources} | to_nice_yaml }}"
  become: true
  notify: restart grafana

- name: Ensure Loki service is started and enabled
  ansible.builtin.systemd:
    name: loki
    state: started
    enabled: true
    daemon_reload: true

- name: Ensure Grafana service is started and enabled
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true
    daemon_reload: true
