---
- name: Install and configure prometheus
  ansible.builtin.import_tasks: prometheus.yaml
  become: true

- name: Install and configure grafana and alloy
  ansible.builtin.import_tasks: grafana.yaml
  become: true

- name: Install and configure borgbackup
  ansible.builtin.import_tasks: backups.yaml
