---
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Create prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    system: true
    shell: /bin/false
    create_home: false

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0755"
  loop:
    - "{{ prometheus_dir_conf }}"
    - "{{ prometheus_dir_data }}"

- name: Download and unpack Prometheus binary
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Copy binaries to final destination
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0755"
  loop:
    - prometheus
    - promtool

- name: Move configuration files
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_dir_conf }}/"
    remote_src: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0755"
  loop:
    - prometheus.yml

- name: Create systemd service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
    content: |
      [Unit]
      Description=Prometheus Monitoring System
      Wants=network-online.target
      After=network-online.target

      [Service]
      User={{ prometheus_user }}
      Group={{ prometheus_user }}
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file={{ prometheus_dir_conf }}/prometheus.yml \
        --storage.tsdb.path={{ prometheus_dir_data }}/ \
        --web.enable-remote-write-receiver

      [Install]
      WantedBy=multi-user.target
  notify: restart prometheus

- name: Ensure Prometheus service is started and enabled
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
