---
- name: reload daemons
  become: true
  ansible.builtin.service:
    daemon_reload: true

- name: restart keepalived
  become: true
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: restart haproxy
  become: true
  ansible.builtin.service:
    name: haproxy
    state: restarted