---
# This is done through shell because proxmox native modules require API token to exist already. Precisely what we are trying to accomplish

- name: Check whether Terraform role exists
  ansible.builtin.command: pveum role list --output-format json
  register: pve_roles
  changed_when: false

- name: Create Terraform role
  ansible.builtin.command: >
    pveum role add Terraform
  when: "'Terraform' not in (pve_roles.stdout | from_json | map(attribute='roleid') | list)"

- name: Modify role Terraform permissions
  ansible.builtin.command: >
    pveum role modify Terraform --privs "{{ terraform_privs | join(',') }}"
  changed_when: false

- name: Check whether Terraform user exists
  ansible.builtin.command: pveum user list --output-format json
  register: pve_users
  changed_when: false

- name: Create Terraform user
  ansible.builtin.command: >
    pveum user add {{ users['prox_terraform_user'] }}
    --comment "Terraform integration user"
    --enable 1
    --expire 0
  when: users['prox_terraform_user'] not in (pve_users.stdout | from_json | map(attribute='userid') | list)

- name: Grant Terraform role on /vms
  ansible.builtin.command: >
    pveum acl modify /vms
    --users {{ users['prox_terraform_user'] }}
    --roles Terraform
    --propagate 1
  changed_when: false

- name: Grant datastore role on /storage/local
  ansible.builtin.command: >
    pveum acl modify /storage/local
    --users {{ users['prox_terraform_user'] }}
    --roles PVEDatastoreAdmin
    --propagate 1
  changed_when: false


- name: Grant datastore role on /storage/local-lvm
  ansible.builtin.command: >
    pveum acl modify /storage/local-lvm
    --users {{ users['prox_terraform_user'] }}
    --roles PVEDatastoreUser
    --propagate 1
  changed_when: false


- name: Check whether Terraform API token exists
  ansible.builtin.command: >
    pveum user token list {{ users['prox_terraform_user'] }} --output-format json
  register: pve_tokens
  changed_when: false

- name: Create Terraform API token
  ansible.builtin.command: >
    pveum user token add {{ users['prox_terraform_user'] }} {{ users['prox_terraform_token_id'] }}
    --comment "Terraform integration"
    --expire 0
    --privsep 0
    --output-format json
  no_log: true
  when: users['prox_terraform_token_id'] not in (pve_tokens.stdout | from_json | map(attribute='tokenid') | list)

- name: Regenerate Terraform API token
  no_log: true
  register: token_rotated
  ansible.builtin.command: pveum user token modify "{{ users['prox_terraform_user'] }}" "{{ users['prox_terraform_token_id'] }}" --regenerate 1 --output-format json

- name: Store generated/regenerated API_TOKEN as parameter in AWS SSM parameter store
  no_log: true
  delegate_to: localhost
  community.aws.ssm_parameter:
    name: /lab/compute/api-token
    string_type: SecureString
    value: "{{ (token_rotated.stdout | from_json).value }}"
    region: us-east-1