---
- name: Setup general config for K8s cluster
  hosts: 
    - k8s_cluster
  roles:
    - k8s

- name: Setup control plane config
  hosts:
    - control_plane
  roles:
    - k8s-control

- name: Setup worker nodes and join them to cluster
  hosts:
    - workers
  roles:
    - k8s-workers

- name: Set up CNI
  hosts:
    - control_plane
  tasks:
    - name: Install Calico CNI
      ansible.builtin.import_role:
        name: k8s-control
        tasks_from: cni