---
- name: Create ArgoCD Application
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "{{ item.name }}"
        namespace: argocd
      spec:
        project: "{{ item.project | default('default') }}"
        source:
          repoURL: "{{ item.repo_url }}"
          targetRevision: "{{ item.branch | default('main') }}"
          path: "{{ item.path }}"
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{ item.namespace }}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
  loop: "{{ argocd_applications }}"